# Generated by Django 3.0.3 on 2020-03-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0002_auto_20200310_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='catagory_id',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='publisher_id',
        ),
    ]
