# Generated by Django 3.0.3 on 2020-03-12 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0003_auto_20200310_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookdata.Author'),
            preserve_default=False,
        ),
    ]
