# Generated by Django 3.0.3 on 2020-03-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0005_catalog_publisher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='catagory_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookdata.Catagory'),
            preserve_default=False,
        ),
    ]
