# Generated by Django 3.0.3 on 2020-04-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0006_catalog_catagory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_id',
            new_name='authorid',
        ),
        migrations.RenameField(
            model_name='catagory',
            old_name='catagory_id',
            new_name='catagoryid',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='book_id',
            new_name='bookid',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='catagory_id',
            new_name='catagoryid',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='publisher_id',
            new_name='publisherid',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='publisher_id',
            new_name='publisherid',
        ),
    ]
