# Generated by Django 3.0.3 on 2020-04-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0007_auto_20200404_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='author_id',
            new_name='authorid',
        ),
    ]
