# Generated by Django 3.0.3 on 2020-04-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0008_auto_20200404_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='authorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookdata.Author'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='catagoryid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookdata.Catagory'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='publisherid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookdata.Publisher'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='bookid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookdata.Catalog'),
        ),
    ]
