# Generated by Django 3.0.3 on 2020-04-05 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0009_auto_20200404_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='bookid',
            field=models.ForeignKey(db_column='bookid', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookdata.Catalog'),
        ),
    ]
