# Generated by Django 3.0.3 on 2020-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0011_auto_20200405_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='price',
            field=models.FloatField(),
        ),
    ]
