
from django.urls import path
from .import views
urlpatterns = [
    path('', views.homepage, name='home'),
    path('registration/', views.register, name='app-register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('login/success', views.success, name='success'),
    path('login/success/choice', views.choice, name='choice'),
    path('login/success/author', views.author, name='author'),
    path('login/success/publisher', views.publisher, name='publisher'),
    path('login/success/catalog', views.catalog, name='catalog'),
    path('login/success/catagory', views.catagory, name='catagory'),
    path('login/success/orderdetails', views.order_details, name='orderdetails'),
    path('login/success/updateprice', views.update_price, name='updateprice'),
    path('login/success/authordetails',
         views.author_details, name='authordetails'),
    path('login/success/maxsales', views.author_maxsales, name='authormaxsales'),
    path('login/success/updatedelete', views.update_delete, name='updatedelete'),
    path('login/success/updatedelete/author',
         views.delete_author, name='deleteauthor'),
    path('login/success/updatedelete/author/authorupdate/<int:pk>/edit',
         views.author_update, name='authorupdate'),
    path('login/success/updatedelete/publisher',
         views.delete_publisher, name='deletepublisher'),
    path('login/success/updatedelete/publisher/publisherupdate/<int:pk>/edit',
         views.update_publisher, name='updatepublisher'),

    path('login/success/updatedelete/catagory',
         views.delete_catagory, name='deletecatagory'),
    path('login/success/updatedelete/catagory/catagoryupdate/<int:pk>/edit',
         views.update_catagory, name='updatecatagory'),
    path('login/success/updatedelete/orderdetails',
         views.delete_orderdetails, name='deleteorderdetails'),
    path('login/success/updatedelete/orderdetails/orderdetailupdate/<int:pk>/edit',
         views.update_orderdetails, name='updateorderdetails'),
    path('login/success/updatedelete/catalogdetails',
         views.delete_catalog, name="deletecatalog"),
    path('login/success/updatedelete/catalogdetails/catalogdetailupdate/<int:pk>/edit',
         views.update_catalog, name="updatecatalog"),

    path('ajax/publisherautocomplete',
         views.publisher_autocomplete, name='publisherautocomplete'),
    path('ajax/authorautocomplete', views.Author_autocomplete,
         name='authorautocomplete'),
    path('ajax/catalogautocomplete', views.catalog_autocomplete,
         name='catalogautocomplete'),
    path('ajax/updatepriceautocomplete',
         views.updateprice_autocomplete, name='updatepriceautocomplete'),

]
